# Generated by Django 5.0 on 2023-12-27 09:26

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_start', models.DateField(db_default=django.db.models.functions.datetime.Now())),
                ('enroll_end', models.DateField()),
                ('course_start', models.DateField()),
                ('course_end', models.DateField()),
                ('stud_min', models.IntegerField(default=1)),
                ('stud_max', models.IntegerField(default=10)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_course', to='school.course')),
            ],
        ),
    ]
