# Generated by Django 5.0 on 2023-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_course_rating_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='enroll_start',
            field=models.DateField(),
        ),
    ]
