# Generated by Django 5.0 on 2023-12-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_enroll_enroll_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='stud_current',
            field=models.IntegerField(default=0),
        ),
    ]
