# Generated by Django 5.0 on 2023-12-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_enroll_stud_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.group'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='course_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='course_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='enroll_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='enroll_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
