# Generated by Django 5.0 on 2023-12-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_group_stud_current_alter_enroll_stud_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='stud_current',
        ),
    ]
