# Generated by Django 5.0 on 2023-12-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_enroll_stud_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='stud_current',
        ),
    ]
