# Generated by Django 5.0 on 2023-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_group_stud_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='stud_current',
            field=models.IntegerField(default=0),
        ),
    ]
