# Generated by Django 5.0 on 2023-12-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_enroll_stud_max_alter_enroll_stud_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rating',
        ),
    ]
